#user-server: http://localhost:8001/auth


server:
    port: 8002
    session:
          timeout: 600
spring:
    application:
        name: account-service

app:
    name: fishbone
    db:
          url: jdbc:mysql://localhost:3306/fishbone?serverTimezone=UTC
          username: root
          password: root

#security:
#    oauth2:
#        resource:
#          token-info-uri: ${user-server}/oauth/check_token
#        client:
#          client-id: demo
#          client-secret: demo
#debug: true
