server:
    port: 8001
    context-path: /auth
    session:
          timeout: 600

app:
    db:
          url: jdbc:mysql://localhost:3306/fishbone?serverTimezone=UTC
          username: root
          password: root
spring:
    application:
        name: user-service

security:
  user:
    password: password
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      scope: read, write
      auto-approve-scopes: .*
    authorization:
      check-token-access: permitAll()
