logger.dir: /home/admin/

#server
server:
    port: 3080
    session:
          timeout: 600

spring:
    application:
        name: sleuth
#    zipkin:
#        base-url: http://127.0.0.1:3080
    sleuth:
        enabled: false
    cloud:
      stream:
        kafka:
          binder:
            brokers: localhost:9092
            zk-nodes: localhost:2181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/
