logger.dir: /home/admin/

#server
server:
    port: 3080
    session:
          timeout: 600

app:
    name: sleuth

spring:
    application:
        name: sleuth

sleuth:
    sampler:
      percentage: 1.0
    cloud:
      stream:
        kafka:
          binder:
            brokers: localhost:9092
            zk-nodes: localhost:2181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/
