logger.dir: /home/admin/

#server
server:
    port: 7080
    session:
          timeout: 600

app:
    name: zuul

spring:
  application:
    name: zuul


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/