logger.dir: /home/admin/

#server
server:
    port: 9080
    session:
          timeout: 600

app:
    name: eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/