logger.dir: /home/admin/

#server
server:
    port: 5080
    session:
          timeout: 600

app:
    name: admin

spring:
  application:
    name: admin-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/

management:
  security:
    enabled: false