server:
    port: 8005
    session:
          timeout: 600
spring:
    application:
        name: idgen-service

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9080/eureka/