logger.dir: /home/admin/

#server
server:
    port: 4080
    session:
          timeout: 600

app:
    name: ribbon

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9080/eureka/